auto: false
pygments: true
lsi: false
markdown: kramdown
exclude: Gemfile, Gemfile.lock, Rakefile

# configuration required for some pages
domain: averyspecialepisode.tv
title: A Very Special Episode

# configuration for ehancements
google_analytics:
  account: UA-29216841-1

github:
  username: nerdhaus

disqus:
  id: avse

typekit:
  code: hon3haq
