<!-- /ht Andy Clarke - http://front.ie/lkCwyf -->
<meta http-equiv="cleartype" content="on">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  
<link rel="shortcut icon" href="/link/to/favicon.ico">
<link rel="apple-touch-icon" href="/link/to/apple-touch-icon.png">

<!-- /ht Jeremy Keith - http://front.ie/mLXiaS -->
<link rel="stylesheet" href="/css/global.css" media="all">
<link rel="stylesheet" href="/css/layout.css" media="all and (min-width: 33.236em)">
<!-- 30em + (1.618em * 2) = 33.236em / Eliminates potential of horizontal scrolling in most cases -->

<!-- Google Fonts & Custom CSS -->
<link href='http://fonts.googleapis.com/css?family=Alfa+Slab+One' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/css/avse.css" media="all">

<!--[if (lt IE 9) & (!IEMobile)]>
<link rel="stylesheet" href="css/example/layout.css" media="all">
<![endif]-->

<script src="/js/libs/modernizr-1.7.min.js"></script>
